name: Test action-clang-tidy workflow

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        reporter: [ github-check, github-pr-review, github-pr-annotations ]

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: CMake
        env:
          CC: clang
        working-directory: test
        run: cmake -B ./build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - uses: ./
        with:
          workdir: ./test/build
          reporter: ${{ matrix.reporter }}
          fail_on_error: false
